export const curveSources = [
  {
    key: 'ust_par_nominal',
    title: 'US Treasury Par',
    url: 'https://home.treasury.gov/resource-center/data-chart-center/interest-rates/pages/xml?data=daily_treasury_yield_curve&field_tdr_date_value=2026',
    kind: 'bootstrap_input',
    market: 'USD',
  },
  {
    key: 'ust_bill_rates',
    title: 'US Treasury Bills',
    url: 'https://home.treasury.gov/resource-center/data-chart-center/interest-rates/pages/xml?data=daily_treasury_bill_rates&field_tdr_date_value=2026',
    kind: 'bootstrap_input',
    market: 'USD',
  },
  {
    key: 'ust_real_par',
    title: 'US Treasury Real (TIPS) Par',
    url: 'https://home.treasury.gov/resource-center/data-chart-center/interest-rates/pages/xml?data=daily_treasury_real_yield_curve&field_tdr_date_value=2026',
    kind: 'bootstrap_input',
    market: 'USD',
  },
  {
    key: 'fred_sofr',
    title: 'US SOFR',
    url: 'https://api.stlouisfed.org/fred/series/observations?series_id=SOFR&api_key=YOUR_FRED_KEY&file_type=json',
    kind: 'front_end_reference',
    market: 'USD',
  },
  {
    key: 'fred_dgs2',
    title: 'US Treasury 2Y (FRED)',
    url: 'https://api.stlouisfed.org/fred/series/observations?series_id=DGS2&api_key=YOUR_FRED_KEY&file_type=json',
    kind: 'benchmark_series',
    market: 'USD',
  },
  {
    key: 'fred_dgs5',
    title: 'US Treasury 5Y (FRED)',
    url: 'https://api.stlouisfed.org/fred/series/observations?series_id=DGS5&api_key=YOUR_FRED_KEY&file_type=json',
    kind: 'benchmark_series',
    market: 'USD',
  },
  {
    key: 'fred_dgs10',
    title: 'US Treasury 10Y (FRED)',
    url: 'https://api.stlouisfed.org/fred/series/observations?series_id=DGS10&api_key=YOUR_FRED_KEY&file_type=json',
    kind: 'benchmark_series',
    market: 'USD',
  },
  {
    key: 'fred_dgs30',
    title: 'US Treasury 30Y (FRED)',
    url: 'https://api.stlouisfed.org/fred/series/observations?series_id=DGS30&api_key=YOUR_FRED_KEY&file_type=json',
    kind: 'benchmark_series',
    market: 'USD',
  },
  {
    key: 'ecb_yc_dataset',
    title: 'ECB Yield Curve Dataset',
    url: 'https://data.ecb.europa.eu/data/datasets/YC',
    kind: 'published_curve_dataset',
    market: 'EUR',
  },
  {
    key: 'ecb_spot_10y_example',
    title: 'ECB Spot Example (10Y)',
    url: 'https://data.ecb.europa.eu/data/datasets/YC/YC.B.U2.EUR.4F.G_N_A.SV_C_YM.SR_10Y',
    kind: 'published_spot_curve',
    market: 'EUR',
  },
];
